package utils

import "errors"

var (
	// Auth & User
	ErrUserNotFound                   = errors.New("pengguna tidak ditemukan")
	ErrUserNotRegistered              = errors.New("email belum terdaftar")
	ErrInvalidEmail                   = errors.New("email tidak valid")
	ErrInvalidPassword                = errors.New("password tidak sesuai")
	ErrPasswordNotMatch               = errors.New("password tidak sesuai")
	ErrEmailAlreadyTaken              = errors.New("email sudah terpakai, silahkan gunakan email lain")
	ErrInvalidCredentials             = errors.New("email atau password tidak valid")
	ErrSessionNotFound                = errors.New("sesi tidak ditemukan")
	ErrSessionBlocked                 = errors.New("sesi telah ditutup")
	ErrSessionExpired                 = errors.New("sesi kadaluarsa")
	ErrTokenMismatched                = errors.New("mismatched refresh token")
	ErrInvalidRefreshToken            = errors.New("refresh token tidak valid")
	ErrUnsupportedGrantType           = errors.New("grant_type tidak didukung")
	ErrCourseNotFound                 = errors.New("kursus tidak ditemukan")
	ErrLessonNotFound                 = errors.New("pelajaran tidak ditemukan")
	ErrModuleNotFound                 = errors.New("modul tidak ditemukan pada kursus")
	ErrInvalidModuleProgress          = errors.New("data progress modul tidak valid")
	ErrInvalidLessonProgress          = errors.New("data progress pelajaran tidak valid")
	ErrModulePrerequisiteNotCompleted = errors.New("modul sebelumnya belum selesai")
	ErrLessonPrerequisiteNotCompleted = errors.New("pelajaran sebelumnya belum selesai")
	ErrLessonCompletionRequiresQuiz   = errors.New("pelajaran hanya dapat diselesaikan dengan lulus question set")
	ErrQuestionSetNotFound            = errors.New("question set tidak ditemukan")
	ErrQuestionSetEmpty               = errors.New("question set belum memiliki pertanyaan")
	ErrInvalidAttempt                 = errors.New("data attempt tidak valid")
	ErrAttemptNotFound                = errors.New("attempt tidak ditemukan")
	ErrAttemptLimitReached            = errors.New("batas maksimal attempt telah tercapai")
	ErrAttemptCooldown                = errors.New("attempt masih dalam masa cooldown")
	ErrAttemptAlreadySubmitted        = errors.New("attempt sudah diselesaikan")
	ErrAttemptExpired                 = errors.New("waktu pengerjaan attempt telah habis")
	ErrUnsupportedQuestionSkill       = errors.New("question set hanya mendukung skill reading dan writing")
	ErrInvalidQuestionConfiguration   = errors.New("konfigurasi pertanyaan tidak dapat dinilai")
)
